name: Flask Bank Automation CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Azure Login with Service Principal JSON
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: bankappacr.azurecr.io
          username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t bankappacr.azurecr.io/flask_bank_app:latest .

      # 5️⃣ Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push bankappacr.azurecr.io/flask_bank_app:latest

      # 6️⃣ Update Azure Web App to use the new image
      - name: Update Azure Web App
        run: |
          az webapp config container set \
            --name bank1 \
            --resource-group bank1-rg \
            --container-image-name bankappacr.azurecr.io/flask_bank_app:latest \
            --container-registry-url https://bankappacr.azurecr.io \
            --container-registry-user ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }} \
            --container-registry-password ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

      # 7️⃣ Restart Web App to apply changes
      - name: Restart Azure Web App
        run: |
          az webapp restart --name bank1 --resource-group bank1-rg
